# Generated by Django 4.0.1 on 2022-04-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuaHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ten_Cua_Hang', models.CharField(max_length=500)),
                ('Ma_Cua_Hang', models.CharField(max_length=50)),
                ('Dia_Chi', models.CharField(max_length=500)),
                ('Ngay_Tao', models.DateTimeField(verbose_name='publish date')),
            ],
        ),
    ]
