# Generated by Django 4.0.1 on 2022-04-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ten_San_Pham', models.CharField(max_length=500)),
                ('Ma_San_Pham', models.CharField(max_length=50)),
            ],
        ),
    ]
